const DATA = [
    // NAME                  , namecode              , platforms          , type     ,"story"
    ["Consul Pazen"          , "consulpazen"         , [["youtube", 71.8]], "comment",],
    ["Zio Clo"               , "zioclo"              , [["youtube", 13.9]], "podcast",],
    ["Je suis pas content"   , "jesuispascontent"    , [["youtube", 322]], "comment",],
    ["Juste milieu"          , "justemilieu"         , [["youtube", 279]], "comment",],
    ["Le raptor"             , "leraptor"            , [["youtube", 736]], "essay",],
    ["Sud Radio"             , "sudradio"            , [["youtube", 674]], "podcast",],
    ["Bertille"              , "bertille"            , [["youtube", 8.72]], "essay",],
    ["Livre noir"            , "livrenoir"           , [["youtube", 297]], "podcast",],
    ["France inter"          , "franceinter"         , [["youtube", 869]], "podcast",],
    ["Le percepteur"         , "lepercepteur"        , [["youtube", 622]], "essay",],
    ["Absol"                 , "absol"               , [["youtube", 391]], "podcast",],
    ["Tronche en biais"      , "troncheenbiais"      , [["youtube", 281]], "essay",],
    ["Monsieur Phi"          , "monsieurphi"         , [["youtube", 285]], "essay",],
    ["Cyrus North"           , "cyrusnorth"          , [["youtube", 703]], "essay",],
    ["Kriss Papillon"        , "krisspapillon"       , [["youtube", 645]], "essay",],
    ["Psyhodelik"            , "psyhodelik"          , [["youtube", 193]], "comment",],
    ["Canard Refractaire"    , "canardrefractaire"   , [["youtube", 165]], "essay",],
    ["AJ+"                   , "aj"                  , [["youtube", 374]], "essay",],
    ["Cemil"                 , "cemil"               , [["youtube", 75.8]], "essay",],
    ["ManonBrill"            , "manonbrill"          , [["youtube", 680]], "essay",],
    ["Idriss Aberkane"       , "idrissaberkane"      , [["youtube", 616]], "essay",],
    ["La Cartouche"          , "lacartouche"         , [["youtube", 58.6]], "essay",],
    ["Stephane Edouard"      , "stephaneedouard"     , [["youtube", 340]], "essay",],
    ["Greg Toussaint"        , "gregtoussaint"       , [["youtube", 327]], "essay",],
    ["Le crayon"             , "lecrayon"            , [["youtube", 74.5]], "podcast",],
    ["Konbini"               , "konbini"             , [["youtube", 1610]], "essay",],
    ["Lapin du futur"        , "lapindufutur"        , [["youtube", 101]], "essay",],
    ["Mos Majorum"           , "mosmajorum"          , [["youtube", 42.2]], "essay",],
    ["Trouble Fait"          , "troublefait"         , [["youtube", 197]], "essay",],
    ["Loic Chaigneau"        , "loicchaigneau"       , [["youtube", 23.7]], "essay",],
    ["Thinkerview"           , "thinkerview"         , [["youtube", 1020]], "podcast",],
    ["Elucid"                , "elucid"              , [["youtube", 90.8]], "podcast",],
    ["Les incorrectibles"    , "incorrectibles"      , [["youtube", 142]], "podcast",],
    ["Tatiana Ventose"       , "tatiana"             , [["youtube", 295]], "essay",],
    ["Francois Boulo"        , "praxis"              , [["youtube", 73.2]], "essay",],
    ["Hugo Decrypte"         , "hugodecrypte"        , [["youtube", 1650]], "essay",],
    ["Dany et raz"           , "danyraz"             , [["youtube", 7.47]], "essay",],
    ["Mediapart"             , "mediapart"           , [["youtube", 597]], "essay",],
    ["Le Média"              , "lemedia"             , [["youtube", 774]], "essay",],
]

const DATAFAV = ["justemilieu", "bertille", "livrenoir", "franceinter", "lepercepteur", "mosmajorum", "elucid", "canardrefractaire"]


const DATAXY = [
  [887, 364],
  [502, 437],
  [709, 193],
  [658, 260],
  [843, 18],
  [764, 32],
  [653, 453],
  [766, 236],
  [296, 12],
  [594, 151],
  [467, 184],
  [358, 262],
  [266, 249],
  [247, 99],
  [712, 108],
  [775, 311],
  [272, 337],
  [188, 249],
  [198, 362],
  [205, 173],
  [777, 137],
  [817, 381],
  [891, 220],
  [954, 228],
  [619, 364],
  [143, -5],
  [959, 351],
  [733, 408],
  [717, 305],
  [780, 446],
  [452, 18],
  [609, 302],
  [729, 360],
  [714, 249],
  [676, 348],
  [369, 0],
  [215, 452],
  [150, 135],
  [321, 88]
]


// Nota Bene 2110

