const DATA = [
    // NAME                  , namecode              , platforms          , type     ,"story"
    ["Consul Pazen"          , "consulpazen"         , [["youtube", 70.4]], "comment",],
    ["Zio Clo"               , "zioclo"              , [["youtube", 12.8]], "podcast",],
    ["Je suis pas content"   , "jesuispascontent"    , [["youtube", 322]], "comment",],
    ["Juste milieu"          , "justemilieu"         , [["youtube", 274]], "comment",],
    ["Le raptor"             , "leraptor"            , [["youtube", 736]], "essay",],
    ["Sud Radio"             , "sudradio"            , [["youtube", 669]], "podcast",],
    ["Bertille"              , "bertille"            , [["youtube", 8.6]], "essay",],
    ["Livre noir"            , "livrenoir"           , [["youtube", 290]], "podcast",],
    ["France inter"          , "franceinter"         , [["youtube", 865]], "podcast",],
    ["Le percepteur"         , "lepercepteur"        , [["youtube", 608]], "essay",],
    ["Absol"                 , "absol"               , [["youtube", 392]], "podcast",],
    ["Tronche en biais"      , "troncheenbiais"      , [["youtube", 280]], "essay",],
    ["Monsieur Phi"          , "monsieurphi"         , [["youtube", 284]], "essay",],
    ["Cyrus North"           , "cyrusnorth"          , [["youtube", 702]], "essay",],
    ["Kriss Papillon"        , "krisspapillon"       , [["youtube", 646]], "essay",],
    ["Psyhodelik"            , "psyhodelik"          , [["youtube", 191]], "comment",],
    ["Canard Refractaire"    , "canardrefractaire"   , [["youtube", 162]], "essay",],
    ["AJ+"                   , "aj"                  , [["youtube", 366]], "essay",],
    ["Cemil"                 , "cemil"               , [["youtube", 76]], "essay",],
    ["ManonBrill"            , "manonbrill"          , [["youtube", 679]], "essay",],
    ["Idriss Aberkane"       , "idrissaberkane"      , [["youtube", 606]], "essay",],
    ["La Cartouche"          , "lacartouche"         , [["youtube", 57.1]], "essay",],
    ["Stephane Edouard"      , "stephaneedouard"     , [["youtube", 333]], "essay",],
    ["Greg Toussaint"        , "gregtoussaint"       , [["youtube", 325]], "essay",],
    ["Le crayon"             , "lecrayon"            , [["youtube", 71.4]], "podcast",],
    ["Konbini"               , "konbini"             , [["youtube", 1590]], "essay",],
    ["Lapin du futur"        , "lapindufutur"        , [["youtube", 100]], "essay",],
    ["Mos Majorum"           , "mosmajorum"          , [["youtube", 42.2]], "essay",],
    ["Trouble Fait"          , "troublefait"         , [["youtube", 196]], "essay",],
    ["Loic Chaigneau"        , "loicchaigneau"       , [["youtube", 23.1]], "essay",],
    ["Thinkerview"           , "thinkerview"         , [["youtube", 1010]], "podcast",],
]

const DATAXY = [
    [887, 364],
    [502, 437],
    [715, 200],
    [658, 260],
    [843, 18],
    [764, 32],
    [653, 453],
    [766, 236],
    [295, 12],
    [594, 151],
    [467, 184],
    [358, 262],
    [266, 249],
    [208, 87],
    [712, 108],
    [775, 311],
    [316, 355],
    [188, 249],
    [212, 401],
    [205, 173],
    [777, 137],
    [817, 381],
    [891, 220],
    [954, 228],
    [619, 364],
    [193, 5],
    [959, 351],
    [733, 408],
    [716, 303],
    [780, 446],
    [438, 19]
  ]
  // Nota Bene 2110
