const DATA = [
    // NAME                  , namecode              , platforms          , type     ,"story"
    ["No Protocol"           , "noprotocol"          , [["youtube", 19.2]], "comment",],
    ["The Authentic Observer", "theauthenticobserver", [["youtube", 57.6]], "essay"  ,],
    ["Kidology"              , "kidology"            , [["youtube", 97.8]], "essay"  ,],
    ["Kat Blaque"            , "katblaque"           , [["youtube", 458 ]], "essay"  ,],
    ["Xhanderhal"            , "xanderhal"           , [["youtube", 71.6]], "comment",],
    ["Vaush"                 , "vaush"               , [["youtube", 406]] , ""       ,],
    ["Triggernometry"        , "triggernometry"      , [["youtube", 337]] , "podcast"   ,],
    ["Just Pearly"           , "justpearlythings"    , [["youtube", 249]] , "podcast"   ,],
    ["Rebel wisdom"          , "rebelwisdom"         , [["youtube", 243]] , "podcast"       ,],
    ["Philosophy Tube"       , "philosophytube"      , [["youtube", 1180]] , "essay"    ,],
    ["Lex Fridman"           , "lexfridman"          , [["youtube", 1960]] , "podcast" ,],
    ["Matt Walsh"            , "mattwalsh"           , [["youtube", 1490]] , "comedy" ,],
    ["Coleman Hughes"        , "colemanhughes"       , [["youtube", 102]] , "podcast" ,],
    ["Some more news"        , "somemorenews"        , [["youtube", 647]] , "comment"       ,],
    ["Trevor noah"           , "trevornoah"          , [["youtube", 10000]] , "comedy"       ,],
    ["Ryan long"             , "ryanlong"            , [["youtube", 559]] , "comedy"        ,],
    ["Aloudy"                , "aloudy"              , [["youtube", 42.5]] , "comment"       ,],
    ["Mikhaila Peterson"     , "mikhailapeterson"    , [["youtube", 691]] , "podcast"        ,],
    ["Jordan Peterson"       , "jordanpeterson"      , [["youtube", 5360]] , "podcast" ,],
    ["Aba & Preach"          , "abapreach"           , [["youtube", 1740]] , "essay"        ,],
    ["Destiny"               , "destiny"             , [["youtube", 455]] , "comment"  ,],
    ["Blaire white"          , "blairewhite"         , [["youtube", 1030]] , ""        ,],
    ["Unherd"                , "unherd"              , [["youtube", 288]] , "podcast"         ,],
    ["The Realignment"       , "therealignment"      , [["youtube", 65.9]] , "podcast" ,],
    ["Brett Cooper"          , "brettcooper"         , [["youtube", 984]] , ""         ,],
    ["Hasan abi"             , "hasanabi"            , [["youtube", 1000]] , "comment"        ,],
    ["Ben Shapiro"           , "benshapiro"          , [["youtube", 4820]] , "podcast" ,],
    ["Bret Weinstein"        , "bretweinstein"       , [["youtube", 422]] , "podcast"  ,],
    ["Steven Crowder"        , "stevencrowder"       , [["youtube", 5700]] , "podcast"        ,],
    ["Awaken JP"             , "awakenjp"            , [["youtube", 2680]] , "comedy"  ,],
    ["Chris Williamson"      , "chriswilliamson"     , [["youtube", 473]] , "podcast"         ,],
    ["Fair"                  , "fair"                , [["youtube", 6.8]] , "essay"         ,],
    ["Ryan Chapman"          , "ryanchapman"         , [["youtube", 83.4]] , "essay"         ,],
    ["Neil Halloran"         , "neilhalloran"        , [["youtube", 305]] , "essay"         ,],
    ["Aubrey Marcus"         , "aubreymarcus"        , [["youtube", 359]] , "podcast"         ,],
    ["Joe rogan"             , "joerogan"            , [["youtube", 12800]] , "podcast"         ,],
    ["Sam Harris"            , "samharris"           , [["youtube", 581]] , "podcast"         ,],
    ["Mr beat"               , "mrbeat"              , [["youtube", 590]] , "essay"         ,],
    ["Russel Brand"          , "russelbrand"         , [["youtube", 5850]] , "essay"         ,],
    ["Gothix"                , "gothix"              , [["youtube", 322]] , "comment"         ,],
    ["FD signifier"          , "fdsignifier"         , [["youtube", 348]] , "essay"         ,],
    ["Gad Saad"              , "gadsaad"             , [["youtube", 244], ["twitter", 528]] , "podcast"         ,],
    ["Alice Cappelle"        , "alicecappelle"       , [["youtube", 213]] , "essay"         ,],
    ["Prager U"              , "prageru"             , [["youtube", 2960]] , "essay"         ,],
    ["Roma Army"             , "romaarmy"            , [["youtube", 945]] , "essay"         ,],
    ["Second Thought"        , "secondthought"       , [["youtube", 1310]] , "essay"         ,],
    ["The roommates"         , "theroommates"        , [["youtube", 526]] , "podcast"         ,],
    ["Khadija Mbowe"         , "khadijambowe"        , [["youtube", 526]] , "essay"         ,],
    ["Monica Hernandez"      , "monicahernandez"     , [["youtube", 96.4]] ,"essay"         ,],
    ["Fresh&fit"             , "freshandfit"         , [["youtube", 844]] , "podcast"         ,],
    ["HealthyGamerGG"        , "healthygamer"        , [["youtube", 988]] , "essay"         ,],
    ["Jammi Dodger"          , "jammidodger"         , [["youtube", 1000]] , "essay"         ,],
    ["Contra Points"         , "contrapoints"        , [["youtube", 1600]] , "essay"         ,],
    ["Noah Samsen"           , "noahsamsen"          , [["youtube", 261]] , "essay"         ,],
    ["Hbomberguy"            , "hbomberguy"          , [["youtube", 1040]] , "essay"         ,],
    ["Sam Collins"           , "samcollins"          , [["youtube", 928]] , "essay"         ,],
    ["Tara Mooknee"          , "taramooknee"         , [["youtube", 438]] , "essay"         ,],
    ["Big Joel"              , "bigjoel"             , [["youtube", 555]] , "essay"         ,],
    ["Pop Culture Detective" , "popculturedetective" , [["youtube", 908]] , "essay"         ,],
    ["Levert Blount"         , "levertthebassman"    , [["tiktok", 738]] , "comment"         ,],
    ["Princess Weekes"       , "princessweekes"      , [["youtube", 165]] , "essay"         ,],
    ["BNC news"              , "bncnews"             , [["youtube", 139]] , "news"         ,],
    ["Ruined Leon"           , "ruinedleon"          , [["youtube", 198]] , "comment"         ,],
    ["The Burger Krieg"      , "theburgerkrieg"      , [["youtube", 32.5]] , "essay"         ,],
    ["JessieGender"          , "jessiegender"        , [["youtube", 163]] , "essay"         ,],
    ["MüneCat"               , "munecat"             , [["youtube", 248]] , "essay"         ,],
    ["Isaac Butterfield"     , "isaacbutterfield"    , [["youtube", 1780]] , "essay"         ,],
    ["Shneako"               , "shneako"             , [["youtube", 693]] , "essay"         ,],
    ["Jreg"                  , "jreg"                , [["youtube", 446]] , "essay"         ,],
    ["Candace Owens"         , "candaceowens"        , [["youtube", 1080]] , "essay"         ,],
]

const DATAXY = [
  [633, 463],
  [453, 422],
  [353, 329],
  [107, 186],
  [37, 409],
  [114, 269],
  [763, 270],
  [906, 332],
  [517, 322],
  [199, 138],
  [560, 44],
  [926, 104],
  [632, 325],
  [43, 149],
  [299, 0],
  [789, 188],
  [928, 426],
  [690, 176],
  [738, 68],
  [659, 41],
  [188, 266],
  [821, 139],
  [541, 236],
  [599, 395],
  [918, 183],
  [124, 88],
  [906, 23],
  [601, 145],
  [974, 10],
  [877, 69],
  [692, 262],
  [575, 483],
  [417, 347],
  [370, 253],
  [621, 230],
  [739, -6],
  [420, 179],
  [161, 165],
  [804, 7],
  [852, 272],
  [38, 285],
  [800, 348],
  [259, 298],
  [824, 70],
  [691, 106],
  [189, 7],
  [743, 134],
  [277, 219],
  [112, 405],
  [858, 197],
  [385, 100],
  [54, 6],
  [122, 4],
  [43, 338],
  [186, 70],
  [56, 80],
  [33, 209],
  [205, 208],
  [270, 84],
  [-9, 107],
  [248, 370],
  [182, 388],
  [849, 420],
  [261, 447],
  [104, 343],
  [159, 333],
  [981, 94],
  [950, 264],
  [347, 185],
  [887, 144]
]
// Not publicy sharing political values ideas
// ProZD 3810
// Hybrid Calisthenic 2970
// Shan Boody 694
// Better ideas 1930
// Anna Akana 2800
// Mina Lee 1100
// Clark Kegley 1140
