const DATA = [
    // NAME                  , namecode              , platforms          , type     ,"story"
    ["No Protocol"           , "noprotocol"          , [["youtube", 27.7]], "comment",],
    ["The Authentic Observer", "theauthenticobserver", [["youtube", 58.4]], "essay"  ,],
    ["Kidology"              , "kidology"            , [["youtube", 103]], "essay"  ,],
    ["Kat Blaque"            , "katblaque"           , [["youtube", 461 ]], "essay"  ,],
    ["Xhanderhal"            , "xanderhal"           , [["youtube", 71.7]], "comment",],
    ["Vaush"                 , "vaush"               , [["youtube", 406]] , ""       ,],
    ["Triggernometry"        , "triggernometry"      , [["youtube", 354]] , "podcast"   ,],
    ["Just Pearly"           , "justpearlythings"    , [["youtube", 320]] , "podcast"   ,],
    ["Rebel wisdom"          , "rebelwisdom"         , [["youtube", 243]] , "podcast"       ,],
    ["Philosophy Tube"       , "philosophytube"      , [["youtube", 1200]] , "essay"    ,],
    ["Lex Fridman"           , "lexfridman"          , [["youtube", 2040]] , "podcast" ,],
    ["Matt Walsh"            , "mattwalsh"           , [["youtube", 1620]] , "comedy" ,],
    ["Coleman Hughes"        , "colemanhughes"       , [["youtube", 102]] , "podcast" ,],
    ["Some more news"        , "somemorenews"        , [["youtube", 662]] , "comment"       ,],
    ["Trevor noah"           , "trevornoah"          , [["youtube", 10100]] , "comedy"       ,],
    ["Ryan long"             , "ryanlong"            , [["youtube", 578]] , "comedy"        ,],
    ["Aloudy"                , "aloudy"              , [["youtube", 47.6]] , "comment"       ,],
    ["Mikhaila Peterson"     , "mikhailapeterson"    , [["youtube", 713]] , "podcast"        ,],
    ["Jordan Peterson"       , "jordanpeterson"      , [["youtube", 5430]] , "podcast" ,],
    ["Aba & Preach"          , "abapreach"           , [["youtube", 1760]] , "essay"        ,],
    ["Destiny"               , "destiny"             , [["youtube", 488]] , "comment"  ,],
    ["Blaire white"          , "blairewhite"         , [["youtube", 1030]] , ""        ,],
    ["Unherd"                , "unherd"              , [["youtube", 290]] , "podcast"         ,],
    ["The Realignment"       , "therealignment"      , [["youtube", 66]] , "podcast" ,],
    ["Brett Cooper"          , "brettcooper"         , [["youtube", 1100]] , ""         ,],
    ["Hasan abi"             , "hasanabi"            , [["youtube", 1030]] , "comment"        ,],
    ["Ben Shapiro"           , "benshapiro"          , [["youtube", 4890]] , "podcast" ,],
    ["Bret Weinstein"        , "bretweinstein"       , [["youtube", 423]] , "podcast"  ,],
    ["Steven Crowder"        , "stevencrowder"       , [["youtube", 5720]] , "podcast"        ,],
    ["Awaken JP"             , "awakenjp"            , [["youtube", 2700]] , "comedy"  ,],
    ["Chris Williamson"      , "chriswilliamson"     , [["youtube", 505]] , "podcast"         ,],
    ["Fair"                  , "fair"                , [["youtube", 6.97]] , "essay"         ,],
    ["Ryan Chapman"          , "ryanchapman"         , [["youtube", 90.2]] , "essay"         ,],
    ["Neil Halloran"         , "neilhalloran"        , [["youtube", 305]] , "essay"         ,],
    ["Aubrey Marcus"         , "aubreymarcus"        , [["youtube", 363]] , "podcast"         ,],
    ["Joe rogan"             , "joerogan"            , [["youtube", 13000]] , "podcast"         ,],
    ["Sam Harris"            , "samharris"           , [["youtube", 582]] , "podcast"         ,],
    ["Mr beat"               , "mrbeat"              , [["youtube", 594]] , "essay"         ,],
    ["Russel Brand"          , "russelbrand"         , [["youtube", 5900]] , "essay"         ,],
    ["Gothix"                , "gothix"              , [["youtube", 322]] , "comment"         ,],
    ["FD signifier"          , "fdsignifier"         , [["youtube", 356]] , "essay"         ,],
    ["Gad Saad"              , "gadsaad"             , [["youtube", 248], ["twitter", 532.7]] , "podcast"         ,],
    ["Alice Cappelle"        , "alicecappelle"       , [["youtube", 217]] , "essay"         ,],
    ["Prager U"              , "prageru"             , [["youtube", 2970]] , "essay"         ,],
    ["Roma Army"             , "romaarmy"            , [["youtube", 985]] , "essay"         ,],
    ["Second Thought"        , "secondthought"       , [["youtube", 1320]] , "essay"         ,],
    ["The roommates"         , "theroommates"        , [["youtube", 527]] , "podcast"         ,],
    ["Khadija Mbowe"         , "khadijambowe"        , [["youtube", 534]] , "essay"         ,],
    ["Monica Hernandez"      , "monicahernandez"     , [["youtube", 97.9]] ,"essay"         ,],
    ["Fresh&fit"             , "freshandfit"         , [["youtube", 884]] , "podcast"         ,],
    ["HealthyGamerGG"        , "healthygamer"        , [["youtube", 994]] , "essay"         ,],
    ["Jammi Dodger"          , "jammidodger"         , [["youtube", 1000]] , "essay"         ,],
    ["Contra Points"         , "contrapoints"        , [["youtube", 1610]] , "essay"         ,],
    ["Noah Samsen"           , "noahsamsen"          , [["youtube", 282]] , "essay"         ,],
    ["Hbomberguy"            , "hbomberguy"          , [["youtube", 1050]] , "essay"         ,],
    ["Sam Collins"           , "samcollins"          , [["youtube", 929]] , "essay"         ,],
    ["Tara Mooknee"          , "taramooknee"         , [["youtube", 441]] , "essay"         ,],
    ["Big Joel"              , "bigjoel"             , [["youtube", 558]] , "essay"         ,],
    ["Pop Culture Detective" , "popculturedetective" , [["youtube", 921]] , "essay"         ,],
    ["Levert Blount"         , "levertthebassman"    , [["tiktok", 750.8]] , "comment"         ,],
    ["Princess Weekes"       , "princessweekes"      , [["youtube", 166]] , "essay"         ,],
    ["BNC news"              , "bncnews"             , [["youtube", 140]] , "news"         ,],
    ["Ruined Leon"           , "ruinedleon"          , [["youtube", 198]] , "comment"         ,],
    ["The Burger Krieg"      , "theburgerkrieg"      , [["youtube", 37.3]] , "essay"         ,],
    ["JessieGender"          , "jessiegender"        , [["youtube", 167]] , "essay"         ,],
    ["MüneCat"               , "munecat"             , [["youtube", 252]] , "essay"         ,],
    ["Isaac Butterfield"     , "isaacbutterfield"    , [["youtube", 1790]] , "essay"         ,],
    ["Shneako"               , "shneako"             , [["youtube", 753]] , "essay"         ,],
    ["Jreg"                  , "jreg"                , [["youtube", 447]] , "comedy"         ,],
    ["Candace Owens"         , "candaceowens"        , [["youtube", 1090]] , "essay"         ,],
    ["Cosmic Skeptic"        , "cosmicskeptic"       , [["youtube", 466]] , "essay"         ,],
    ["Hamza"                 , "hamza"               , [["youtube", 756]] , "essay"         ,],
    ["Emma Thorne"           , "emmathorne"          , [["youtube", 106]] , "essay"         ,],
    ["Arielle Scarcella"     , "ariellescarcella"    , [["youtube", 726]] , "essay"         ,],
    ["Karolina Żebrowska"    , "karolinazeb"         , [["youtube", 1250]] , "essay"         ,],
    ["Tyler Fisher"          , "tylerfischer"        , [["youtube", 169]] , "comedy"         ,],
    ["Amala Ekpunobi"        , "amalaekpunobi"        , [["youtube", 494]] , "comment"         ,],
]

const DATAFAV = ["noprotocol", "kidology", "rebelwisdom", "lexfridman", "colemanhughes", "trevornoah", "jordanpeterson", "chriswilliamson", "fair", "ryanchapman", "unherd", "aubreymarcus", "noahsamsen", "bretweinstein"]


const DATAXY = [
  [642, 459],
  [453, 422],
  [353, 329],
  [107, 186],
  [37, 409],
  [114, 269],
  [860, 307],
  [938, 322],
  [517, 322],
  [199, 138],
  [560, 44],
  [997, 112],
  [620, 301],
  [43, 149],
  [299, 0],
  [785, 209],
  [1019, 433],
  [690, 183],
  [820, 6],
  [659, 41],
  [314, 264],
  [887, 136],
  [541, 236],
  [600, 368],
  [989, 178],
  [124, 88],
  [966, 32],
  [615, 136],
  [1036, 6],
  [901, 55],
  [748, 279],
  [575, 483],
  [417, 347],
  [381, 263],
  [617, 210],
  [744, -9],
  [420, 179],
  [161, 165],
  [783, 61],
  [974, 279],
  [38, 285],
  [805, 333],
  [259, 298],
  [848, 80],
  [691, 106],
  [189, 7],
  [760, 137],
  [271, 195],
  [112, 405],
  [882, 202],
  [385, 100],
  [54, 6],
  [122, 4],
  [43, 338],
  [186, 70],
  [56, 80],
  [33, 209],
  [202, 202],
  [270, 84],
  [-9, 107],
  [248, 370],
  [182, 388],
  [921, 405],
  [298, 475],
  [104, 343],
  [159, 333],
  [1047, 89],
  [940, 208],
  [349, 201],
  [934, 126],
  [739, 211],
  [821, 143],
  [297, 403],
  [835, 213],
  [249, 19],
  [803, 406],
  [865, 268]
]


// Not publicy sharing much political values ideas
// ProZD 3810
// Hybrid Calisthenic 2970
// Shan Boody 694
// Better ideas 1930
// Anna Akana 2800
// Mina Lee 1100
// Clark Kegley 1140


