const DATA = [
    // NAME                  , namecode              , platforms          , type     ,"story"
    ["No Protocol"           , "noprotocol"          , [["youtube", 19.2]], "comment",],
    ["The Authentic Observer", "theauthenticobserver", [["youtube", 57.6]], "essay"  ,],
    ["Kidology"              , "kidology"            , [["youtube", 97.8]], "essay"  ,],
    ["Kat Blaque"            , "katblaque"           , [["youtube", 458 ]], "essay"  ,],
    ["Xhanderhal"            , "xanderhal"           , [["youtube", 71.6]], "comment",],
    ["Vaush"                 , "vaush"               , [["youtube", 406]] , ""       ,],
    ["Triggernometry"        , "triggernometry"      , [["youtube", 337]] , "podcast"   ,],
    ["Just Pearly"           , "justpearlythings"    , [["youtube", 249]] , "podcast"   ,],
    ["Rebel wisdom"          , "rebelwisdom"         , [["youtube", 243]] , "podcast"       ,],
    ["Philosophy Tube"       , "philosophytube"      , [["youtube", 1180]] , "essay"    ,],
    ["Lex Fridman"           , "lexfridman"          , [["youtube", 1960]] , "podcast" ,],
    ["Matt Walsh"            , "mattwalsh"           , [["youtube", 1490]] , "comedy" ,],
    ["Coleman Hughes"        , "colemanhughes"       , [["youtube", 102]] , "podcast" ,],
    ["Some more news"        , "somemorenews"        , [["youtube", 647]] , "comment"       ,],
    ["Trevor noah"           , "trevornoah"          , [["youtube", 10000]] , "comedy"       ,],
    ["Ryan long"             , "ryanlong"            , [["youtube", 559]] , "comedy"        ,],
    ["Aloudy"                , "aloudy"              , [["youtube", 42.5]] , "comment"       ,],
    ["Mikhaila Peterson"     , "mikhailapeterson"    , [["youtube", 691]] , "podcast"        ,],
    ["Jordan Peterson"       , "jordanpeterson"      , [["youtube", 5360]] , "podcast" ,],
    ["Aba & Preach"          , "abapreach"           , [["youtube", 1740]] , "essay"        ,],
    ["Destiny"               , "destiny"             , [["youtube", 455]] , "comment"  ,],
    ["Blaire white"          , "blairewhite"         , [["youtube", 1030]] , ""        ,],
    ["Unherd"                , "unherd"              , [["youtube", 288]] , "podcast"         ,],
    ["The Realignment"       , "therealignment"      , [["youtube", 65.9]] , "podcast" ,],
    ["Brett cooper"          , "brettcooper"         , [["youtube", 984]] , ""         ,],
    ["Hasan abi"             , "hasanabi"            , [["youtube", 1000]] , "comment"        ,],
    ["Ben Shapiro"           , "benshapiro"          , [["youtube", 4820]] , "podcast" ,],
    ["Bret Weinstein"        , "bretweinstein"       , [["youtube", 422]] , "podcast"  ,],
    ["Steven Crowder"        , "stevencrowder"       , [["youtube", 5700]] , "podcast"        ,],
    ["Awaken JP"             , "awakenjp"            , [["youtube", 2680]] , "comedy"  ,],
    ["Chris Williamson"      , "chriswilliamson"     , [["youtube", 473]] , "podcast"         ,],
    ["Fair"                  , "fair"                , [["youtube", 6.8]] , "essay"         ,],
    ["Ryan Chapman"          , "ryanchapman"         , [["youtube", 83.4]] , "essay"         ,],
    ["Neil Halloran"         , "neilhalloran"        , [["youtube", 305]] , "essay"         ,],
    ["Aubrey Marcus"         , "aubreymarcus"        , [["youtube", 359]] , "podcast"         ,],
    ["Joe rogan"             , "joerogan"            , [["youtube", 12800]] , "podcast"         ,],
    ["Sam Harris"            , "samharris"           , [["youtube", 581]] , "podcast"         ,],
    ["Mr beat"               , "mrbeat"              , [["youtube", 590]] , "essay"         ,],
    ["Russel Brand"          , "russelbrand"         , [["youtube", 5850]] , "essay"         ,],
]

const DATAXY = [
    [615, 455],
    [453, 391],
    [518, 297],
    [232, 184],
    [65, 440],
    [223, 277],
    [797, 255],
    [894, 329],
    [534, 225],
    [302, 91],
    [560, 44],
    [926, 104],
    [627, 302],
    [50, 149],
    [331, 7],
    [790, 167],
    [928, 426],
    [700, 153],
    [756, 59],
    [673, 81],
    [102, 243],
    [837, 124],
    [495, 163],
    [530, 388],
    [870, 203],
    [154, 103],
    [906, 23],
    [602, 148],
    [974, 10],
    [864, 75],
    [708, 241],
    [548, 461],
    [389, 312],
    [325, 219],
    [614, 234],
    [663, 13],
    [385, 177],
    [160, 215],
    [796, 23]
  ]
// Not publicy sharing political values ideas
// ProZD 3810
// Hybrid Calisthenic 2970
// Shan Boody 694
// Better ideas 1930
